# Video network config
videonet:
    videonet_name: FRCNNVideoModel
    videonet_config:
      backbone_type: resnet
      relu_type: prelu
      width_mult: 1.0
      pretrain: pretrain_zoo/frcnn_128_512.backbone.pth.tar
audionet:
    audionet_name: av_TFGridNetV3_causal
    audionet_config:
        causal: False
        n_fft: 256
        stride: 128
        window: "hann"
        use_builtin_complex: False
        n_srcs:  1
        n_imics: 1
        n_layers: 6
        lstm_hidden_units: 192
        attn_n_head: 4
        attn_qk_output_channel: 4
        emb_dim: 48
        emb_ks: 4
        emb_hs: 1
        activation: "prelu"
      
           
# Loss config
loss:
  train:
    loss_func: PITLossWrapper
    sdr_type: pairwise_neg_snr  #pairwise_neg_sisdr
    config:
      pit_from: pw_mtx
      threshold_byloss: false   #false
  val:
    loss_func: PITLossWrapper
    sdr_type: pairwise_neg_sisdr   #pairwise_neg_sisdr
    config:
      pit_from: pw_mtx
      threshold_byloss: false

# Training config
training:
  system: AudioVisualLightningModule
  gpus: [2, 3, 4, 5]
  parallel: ddp
  epochs: 500
  early_stop:
    monitor: val_loss/dataloader_idx_0
    mode: min
    patience: 15
    verbose: true
  
# Optim config
optimizer:
  optim_name: Adam
  lr: 0.001
  #amsgrad: True
  #weight_decay: 0.1

# Sche config
scheduler: 
  sche_name: ReduceLROnPlateau
  sche_config:
    patience: 10
    factor: 0.5

# Data config
datamodule:
  data_name: AVSpeechDataModule
  data_config:
    train_dir: /home/data3/Contrast_Exp/DataPreProcess/LRS2/tr
    valid_dir: /home/data3/Contrast_Exp/DataPreProcess/LRS2/cv
    test_dir: /home/data3/Contrast_Exp/DataPreProcess/LRS2/tt
    n_src: 1
    sample_rate: 16000
    segment: 2.0
    normalize_audio: false
    batch_size: 8
    num_workers: 6
    pin_memory: true
    persistent_workers: false

    
exp:
  exp_name: av_TFGridNetV3_causal_LRS2
