# Video network config
videonet:
    videonet_name: FRCNNVideoModel
    videonet_config:
      backbone_type: resnet
      relu_type: prelu
      width_mult: 1.0
      pretrain: pretrain_zoo/frcnn_128_512.backbone.pth.tar
audionet:
    audionet_name: AV_Dprnn_Causal
    audionet_config:
      N: 256
      L: 40
      B: 64
      H: 128
      K: 100
      R: 6
      emb_size: 512

# Loss config
loss:
  train:
    loss_func: PITLossWrapper
    sdr_type: pairwise_neg_snr
    config:
      pit_from: pw_mtx
      threshold_byloss: true
  val:
    loss_func: PITLossWrapper
    sdr_type: pairwise_neg_sisdr
    config:
      pit_from: pw_mtx
      threshold_byloss: false

# Training config
training:
  system: AudioVisualLightningModule
  gpus: [2, 4, 5, 6]
  parallel: ddp
  epochs: 500
  early_stop:
    monitor: val_loss/dataloader_idx_0
    mode: min
    patience: 15
    verbose: true
  
# Optim config
optimizer:
  optim_name: adamw
  lr: 0.001
  weight_decay: 0.1

# Sche config
scheduler: 
  sche_name: ReduceLROnPlateau
  sche_config:
    patience: 10
    factor: 0.5

# Data config
datamodule:
  data_name: AVSpeechDataModule
  data_config:
    train_dir: /home/data2/DataPreProcess/LRS2/tr
    valid_dir: /home/data2/DataPreProcess/LRS2/cv
    test_dir: /home/data2/DataPreProcess/LRS2/tt
    n_src: 1
    sample_rate: 16000
    segment: 2.0
    normalize_audio: false
    batch_size: 4
    num_workers: 8
    pin_memory: true
    persistent_workers: false
    
exp:
  exp_name: avdprnn_causal_LRS2
